const genericErrorBlock = (error, res) => {
  // Returns a generic error message generated by errorHandler
  return res.status(401).json({
    message: errorHandler.getErrorMessage(error),
  });
};

const unAuthorizedErrorBlock = (res) => {
  // Returns error when user is authorised to a particular route
  return res.status(403).json({
    message: "Unauthorized user",
  });
};

module.exports = { genericErrorBlock, unAuthorizedErrorBlock };
